### ISSUE TITLE
[DeepSea CI] Stage 4 reproducibly fails at RGW bucket creation

### ISSUE THREAD

**Issue by smithfarm** [SUSE/DeepSea#1580]
### Description of Issue/Question

The DeepSea PR CI (for PRs targeting master) recently started to see failures like this:

CLI:

```
019-03-25T10:15:16.911 INFO:teuthology.orchestra.run.target192168000018.stdout:Failures summary:
2019-03-25T10:15:16.911 INFO:teuthology.orchestra.run.target192168000018.stdout:ceph.rgw.buckets (/srv/salt/ceph/rgw/buckets):
2019-03-25T10:15:16.912 INFO:teuthology.orchestra.run.target192168000018.stdout:  target192168000018.teuthology:
2019-03-25T10:15:16.912 INFO:teuthology.orchestra.run.target192168000018.stdout:    create demo bucket for demo: Module function rgw.create_bucket threw an exception. Exception: [Errno 111] Connection refused
2019-03-25T10:15:16.912 INFO:teuthology.orchestra.run.target192168000018.stdout:    create demo bucket for demo1: Module function rgw.create_bucket threw an exception. Exception: [Errno 111] Connection refused
```

non-CLI:

```
2019-03-25T10:25:20.163 INFO:teuthology.orchestra.run.target192168000004.stdout:----------
2019-03-25T10:25:20.163 INFO:teuthology.orchestra.run.target192168000004.stdout:          ID: rgw demo buckets
2019-03-25T10:25:20.163 INFO:teuthology.orchestra.run.target192168000004.stdout:    Function: salt.state
2019-03-25T10:25:20.163 INFO:teuthology.orchestra.run.target192168000004.stdout:      Result: False
2019-03-25T10:25:20.163 INFO:teuthology.orchestra.run.target192168000004.stdout:     Comment: Run failed on minions: target192168000004.teuthology
2019-03-25T10:25:20.164 INFO:teuthology.orchestra.run.target192168000004.stdout:     Started: 10:18:24.512374
2019-03-25T10:25:20.164 INFO:teuthology.orchestra.run.target192168000004.stdout:    Duration: 140975.18 ms
2019-03-25T10:25:20.164 INFO:teuthology.orchestra.run.target192168000004.stdout:     Changes:
2019-03-25T10:25:20.164 INFO:teuthology.orchestra.run.target192168000004.stdout:              target192168000004.teuthology:
2019-03-25T10:25:20.164 INFO:teuthology.orchestra.run.target192168000004.stdout:                Name: install rgw - Function: pkg.installed - Result: Clean Started: - 10:18:36.361391 Duration: 3657.045 ms
2019-03-25T10:25:20.164 INFO:teuthology.orchestra.run.target192168000004.stdout:              ----------
2019-03-25T10:25:20.165 INFO:teuthology.orchestra.run.target192168000004.stdout:                        ID: create demo bucket for demo
2019-03-25T10:25:20.165 INFO:teuthology.orchestra.run.target192168000004.stdout:                  Function: module.run
2019-03-25T10:25:20.165 INFO:teuthology.orchestra.run.target192168000004.stdout:                      Name: rgw.create_bucket
2019-03-25T10:25:20.165 INFO:teuthology.orchestra.run.target192168000004.stdout:                    Result: False
2019-03-25T10:25:20.165 INFO:teuthology.orchestra.run.target192168000004.stdout:                   Comment: Module function rgw.create_bucket threw an exception. Exception: [Errno 111] Connection refused
2019-03-25T10:25:20.166 INFO:teuthology.orchestra.run.target192168000004.stdout:                   Started: 10:18:40.020410
2019-03-25T10:25:20.166 INFO:teuthology.orchestra.run.target192168000004.stdout:                  Duration: 52072.976 ms
2019-03-25T10:25:20.166 INFO:teuthology.orchestra.run.target192168000004.stdout:                   Changes:
2019-03-25T10:25:20.166 INFO:teuthology.orchestra.run.target192168000004.stdout:              ----------
2019-03-25T10:25:20.166 INFO:teuthology.orchestra.run.target192168000004.stdout:                        ID: create demo bucket for demo1
2019-03-25T10:25:20.166 INFO:teuthology.orchestra.run.target192168000004.stdout:                  Function: module.run
2019-03-25T10:25:20.167 INFO:teuthology.orchestra.run.target192168000004.stdout:                      Name: rgw.create_bucket
2019-03-25T10:25:20.167 INFO:teuthology.orchestra.run.target192168000004.stdout:                    Result: False
2019-03-25T10:25:20.167 INFO:teuthology.orchestra.run.target192168000004.stdout:                   Comment: Module function rgw.create_bucket threw an exception. Exception: [Errno 111] Connection refused
2019-03-25T10:25:20.167 INFO:teuthology.orchestra.run.target192168000004.stdout:                   Started: 10:19:32.093866
2019-03-25T10:25:20.167 INFO:teuthology.orchestra.run.target192168000004.stdout:                  Duration: 73363.159 ms
2019-03-25T10:25:20.167 INFO:teuthology.orchestra.run.target192168000004.stdout:                   Changes:
2019-03-25T10:25:20.168 INFO:teuthology.orchestra.run.target192168000004.stdout:
2019-03-25T10:25:20.168 INFO:teuthology.orchestra.run.target192168000004.stdout:              Summary for target192168000004.teuthology
2019-03-25T10:25:20.168 INFO:teuthology.orchestra.run.target192168000004.stdout:              ------------
2019-03-25T10:25:20.168 INFO:teuthology.orchestra.run.target192168000004.stdout:              Succeeded: 1
2019-03-25T10:25:20.168 INFO:teuthology.orchestra.run.target192168000004.stdout:              Failed:    2
2019-03-25T10:25:20.168 INFO:teuthology.orchestra.run.target192168000004.stdout:              ------------
2019-03-25T10:25:20.169 INFO:teuthology.orchestra.run.target192168000004.stdout:              Total states run:     3
2019-03-25T10:25:20.169 INFO:teuthology.orchestra.run.target192168000004.stdout:              Total run time: 129.093 s
```

The issue seems to appear more frequently when the ECP (internal, R&D) network slows down.

We could think about how to make the `rgw.create_bucket` module more robust by having it try to connect to the RGW gateway several times in a row with a short timeout.

**Comment by smithfarm** [comment]
The function where the try-wait loop would need to be implemented is:

```
def create_bucket(**kwargs):
    """ 
    Create a bucket for a user
    """
    s3conn = s3connect(kwargs['user'])
    if s3conn is None:
        return False
    try:
        s3conn.create_bucket(kwargs['bucket_name'])
    except boto.exception.S3CreateError:
        return False
    return True
```

@theanalyst Do you know which of the two `return False` statements is getting triggered here?

**Comment by smithfarm** [comment]
D'oh, the error says "threw an exception". I guess the retry loop is needed around the `try` clause, not the initial S3 connection attempt.

**Comment by smithfarm** [comment]
```
2019-03-25T14:04:49.048 INFO:teuthology.orchestra.run.target192168000054.stdout:Mar 25 13:59:58 target192168000054 salt-minion[1142]: [ERROR   ] Other boto exception
2019-03-25T14:04:49.048 INFO:teuthology.orchestra.run.target192168000054.stdout:Mar 25 13:59:58 target192168000054 salt-minion[1142]: Traceback (most recent call last):
2019-03-25T14:04:49.048 INFO:teuthology.orchestra.run.target192168000054.stdout:Mar 25 13:59:58 target192168000054 salt-minion[1142]:   File "/var/cache/salt/minion/extmods/modules/rgw.py", line 315, in create_bucket
2019-03-25T14:04:49.048 INFO:teuthology.orchestra.run.target192168000054.stdout:Mar 25 13:59:58 target192168000054 salt-minion[1142]:     s3conn.create_bucket(kwargs['bucket_name'])
2019-03-25T14:04:49.048 INFO:teuthology.orchestra.run.target192168000054.stdout:Mar 25 13:59:58 target192168000054 salt-minion[1142]:   File "/usr/lib/python3.6/site-packages/boto/s3/connection.py", line 619, in create_bucket
2019-03-25T14:04:49.049 INFO:teuthology.orchestra.run.target192168000054.stdout:Mar 25 13:59:58 target192168000054 salt-minion[1142]:     data=data)
2019-03-25T14:04:49.049 INFO:teuthology.orchestra.run.target192168000054.stdout:Mar 25 13:59:58 target192168000054 salt-minion[1142]:   File "/usr/lib/python3.6/site-packages/boto/s3/connection.py", line 671, in make_request
2019-03-25T14:04:49.049 INFO:teuthology.orchestra.run.target192168000054.stdout:Mar 25 13:59:58 target192168000054 salt-minion[1142]:     retry_handler=retry_handler
2019-03-25T14:04:49.049 INFO:teuthology.orchestra.run.target192168000054.stdout:Mar 25 13:59:58 target192168000054 salt-minion[1142]:   File "/usr/lib/python3.6/site-packages/boto/connection.py", line 1071, in make_request
2019-03-25T14:04:49.049 INFO:teuthology.orchestra.run.target192168000054.stdout:Mar 25 13:59:58 target192168000054 salt-minion[1142]:     retry_handler=retry_handler)
2019-03-25T14:04:49.049 INFO:teuthology.orchestra.run.target192168000054.stdout:Mar 25 13:59:58 target192168000054 salt-minion[1142]:   File "/usr/lib/python3.6/site-packages/boto/connection.py", line 1030, in _mexe
2019-03-25T14:04:49.050 INFO:teuthology.orchestra.run.target192168000054.stdout:Mar 25 13:59:58 target192168000054 salt-minion[1142]:     raise ex
2019-03-25T14:04:49.050 INFO:teuthology.orchestra.run.target192168000054.stdout:Mar 25 13:59:58 target192168000054 salt-minion[1142]:   File "/usr/lib/python3.6/site-packages/boto/connection.py", line 943, in _mexe
2019-03-25T14:04:49.050 INFO:teuthology.orchestra.run.target192168000054.stdout:Mar 25 13:59:58 target192168000054 salt-minion[1142]:     request.body, request.headers)
2019-03-25T14:04:49.050 INFO:teuthology.orchestra.run.target192168000054.stdout:Mar 25 13:59:58 target192168000054 salt-minion[1142]:   File "/usr/lib64/python3.6/http/client.py", line 1239, in request
2019-03-25T14:04:49.050 INFO:teuthology.orchestra.run.target192168000054.stdout:Mar 25 13:59:58 target192168000054 salt-minion[1142]:     self._send_request(method, url, body, headers, encode_chunked)
2019-03-25T14:04:49.050 INFO:teuthology.orchestra.run.target192168000054.stdout:Mar 25 13:59:58 target192168000054 salt-minion[1142]:   File "/usr/lib64/python3.6/http/client.py", line 1285, in _send_request
2019-03-25T14:04:49.051 INFO:teuthology.orchestra.run.target192168000054.stdout:Mar 25 13:59:58 target192168000054 salt-minion[1142]:     self.endheaders(body, encode_chunked=encode_chunked)
2019-03-25T14:04:49.051 INFO:teuthology.orchestra.run.target192168000054.stdout:Mar 25 13:59:58 target192168000054 salt-minion[1142]:   File "/usr/lib64/python3.6/http/client.py", line 1234, in endheaders
2019-03-25T14:04:49.051 INFO:teuthology.orchestra.run.target192168000054.stdout:Mar 25 13:59:58 target192168000054 salt-minion[1142]:     self._send_output(message_body, encode_chunked=encode_chunked)
2019-03-25T14:04:49.051 INFO:teuthology.orchestra.run.target192168000054.stdout:Mar 25 13:59:58 target192168000054 salt-minion[1142]:   File "/usr/lib64/python3.6/http/client.py", line 1026, in _send_output
2019-03-25T14:04:49.051 INFO:teuthology.orchestra.run.target192168000054.stdout:Mar 25 13:59:58 target192168000054 salt-minion[1142]:     self.send(msg)
2019-03-25T14:04:49.051 INFO:teuthology.orchestra.run.target192168000054.stdout:Mar 25 13:59:58 target192168000054 salt-minion[1142]:   File "/usr/lib64/python3.6/http/client.py", line 964, in send
2019-03-25T14:04:49.052 INFO:teuthology.orchestra.run.target192168000054.stdout:Mar 25 13:59:58 target192168000054 salt-minion[1142]:     self.connect()
2019-03-25T14:04:49.052 INFO:teuthology.orchestra.run.target192168000054.stdout:Mar 25 13:59:58 target192168000054 salt-minion[1142]:   File "/usr/lib64/python3.6/http/client.py", line 936, in connect
2019-03-25T14:04:49.052 INFO:teuthology.orchestra.run.target192168000054.stdout:Mar 25 13:59:58 target192168000054 salt-minion[1142]:     (self.host,self.port), self.timeout, self.source_address)
2019-03-25T14:04:49.052 INFO:teuthology.orchestra.run.target192168000054.stdout:Mar 25 13:59:58 target192168000054 salt-minion[1142]:   File "/usr/lib64/python3.6/socket.py", line 724, in create_connection
2019-03-25T14:04:49.052 INFO:teuthology.orchestra.run.target192168000054.stdout:Mar 25 13:59:58 target192168000054 salt-minion[1142]:     raise err
2019-03-25T14:04:49.052 INFO:teuthology.orchestra.run.target192168000054.stdout:Mar 25 13:59:58 target192168000054 salt-minion[1142]:   File "/usr/lib64/python3.6/socket.py", line 713, in create_connection
2019-03-25T14:04:49.052 INFO:teuthology.orchestra.run.target192168000054.stdout:Mar 25 13:59:58 target192168000054 salt-minion[1142]:     sock.connect(sa)
2019-03-25T14:04:49.053 INFO:teuthology.orchestra.run.target192168000054.stdout:Mar 25 13:59:58 target192168000054 salt-minion[1142]: ConnectionRefusedError: [Errno 111] Connection refused
```

**Comment by smithfarm** [comment]
In the DeepSea CI it fails every time. In the devel-6.0 and product-6.0 CIs the issue is not reproducing - yet.

**Comment by smithfarm** [comment]
It looks like the "Connection Refused" error is coming from node_exporter? The following message appears in the log when the Connection Refused happens in `create_buckets`, which seems weird:

```
2019-03-25T16:07:46.883 INFO:teuthology.orchestra.run.target192168000035.stdout:Mar 25 15:35:30 target192168000035 salt-minion[1138]: [WARNING ] Could not create RGW bucket via S3 (attempt 3)
2019-03-25T16:07:46.884 INFO:teuthology.orchestra.run.target192168000035.stdout:Mar 25 15:35:30 target192168000035 salt-minion[1138]: [INFO    ] S3 failure possibly transient - waiting 40 seconds before retry
2019-03-25T16:07:46.884 INFO:teuthology.orchestra.run.target192168000035.stdout:Mar 25 15:35:33 target192168000035 node_exporter[4717]: time="2019-03-25T15:35:33Z" level=error msg="ERROR: ntp collector failed after 0.000204s: couldn't get SNTP reply: read udp 127.0.0.1:44309->127.0.0.1:123: read: connection refused" source="collector.go:132"
```

**Comment by smithfarm** [comment]
Reproducible on tip of master when installed in SLE-15-SP1 using `make install`.

Next I will try to prepare an environment where the issue is reproducing, but this should be easy to reproduce in vagrant as well...

**Comment by smithfarm** [comment]
Bisect:

- [x] v0.9.15 tag (PASS)
- [ ] 8f8f44a4 Merge pull request #1570 from rjfd/wip-cli-fix-prometheus
- [ ] 12b291cd Merge pull request #1577 from smithfarm/wip-fix-functests-symlink
- [ ] f7cc9bd7 Merge pull request #1474 from votdev/blinking_lights
- [ ] 4271fb2d Merge pull request #1568 from smithfarm/wip-msgr2
- [ ] 8cb39d7e Merge pull request #1575 from rjfd/wip-cli-fix-python2-stderr-redirect
- [ ] 1ddf5463 Merge pull request #1576 from rjfd/wip-cli-wrap-lines
- [ ] 778f8a00 Merge pull request #1578 from SUSE/wip-ipv6
- [ ] 3738bca9 (HEAD -> master, suse/master) Merge pull request #1579 from smithfarm/wip-cepg

**Comment by smithfarm** [comment]
Abhi and I debugged this today, and we found the root cause: the "Support IPv6" feature changes how "rgw endpoints" is set (to `[::]:80`) but the "endpoints" method in the rgw.py module cannot parse this correctly, so it ends up falling back to port 7480. Since RGW is listening on port 80, boto gets "Connection refused".
